### ISSUE TITLE
Reconcile EnumerateChildrenAsync with EnumerateChildren

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-merkledag#40]
EnumerateChildrenAsync visits the root node, EnumerateChildren doesn't. This is probably causing several subtle bugs but fixing it could cause other subtle bugs.

**Comment by MichaelMure** [comment]
Addressed in https://github.com/ipfs/go-merkledag/pull/42

**Comment by MichaelMure** [comment]
This can be closed now.
