### ISSUE TITLE
Make getPBNode Public 

### ISSUE THREAD

**Issue by postables** [ipfs/go-merkledag#48]
This function https://github.com/ipfs/go-merkledag/blob/master/coding.go#L60 should be public, since it has significant usability elsewhere. For example if using gRPC services, with a public `getPBNode`, the protocol buffer could be returned directly, instead of needing to use a translation layer.

Note, I would be happy to add this functionality if a pr would be accepted

**Comment by Stebalien** [comment]
SGTM. Note: this method _does_ take a reference to the data slice without copying it. That's probably fine but we should note that in the function documentation.

**Comment by postables** [comment]
we could always have a function like `SafeGetPBNode` that does something roughly like:

```
func (n *ProtoNode) SafeGetPBNode() *pb.PBNode {
	nn := new(ProtoNode)
	copy(nn.data, n.data)
	return nn.getPBNode()
}
```

this would prevent accidental use of `getPBNode` and modifying the data slice unintentionally, or maybe even by a goroutine.

**Comment by Stebalien** [comment]
Honestly, I'm fine leaving it as-is as we never _internally_ mutate the data. We always just replace it.

We should just:

1. Document this.
2. Tell users to call `ProtoNode.Copy()` before calling `GetPBNode` if they plan on mutating the data of the original node.

**Comment by postables** [comment]
Sounds good, I'll submit the PR today then :ok_hand:
