### ISSUE TITLE
`(*ProtoNode).RawData` use incorrectly panic instead of returning

### ISSUE THREAD

**Issue by Jorropo** [ipfs/go-merkledag#90]
Where this was found: https://github.com/ipfs/kubo/issues/9297

`(*ProtoNode).RawData` use incorrectly panics, there are cases where consumers can because of bad options trigger an error.

My dumb first instict would be to make it return `([]byte, error)` but AFAIT this is trying to fit an interface so we can't do this.

I guess the alternative is to do the serialisation in the write functions (which do return errors) and save the serialised bytes instead.

**Comment by rvagg** [comment]
Gentle approach: https://github.com/ipfs/go-merkledag/pull/91

Proper approach is to stick an `error` on that return and accept the breakage. There's going to be a lot of breakage from that, but that might be a price worth paying to get rid of a panic. I'm confident that #91 gets the majority case, but there's things it won't catch (mentioned there), but also if the hasher is just plain broken in some way beyond not just being registered! Should that rightly be classified as a runtime error? :shrug: Maybe a broken hasher should panic?

**Comment by rvagg** [comment]
#91 and #92 should address this
